app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | This route group applies the "web" middleware group to every route
  | it contains. The "web" middleware group is defined in your HTTP
  | kernel and includes session state, CSRF protection, and more.
  |
 */

Route::group(['middleware' => ['web']], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');

    Route::get('/', function () {
        return view('welcome');
    });
    
    
    /*Rutas Estado*****************************************/
//    Route::get('/estado','EstadoController@index');
//    Route::post('/estado/create','EstadoController@create');
    //Route::get('/estado','EstadoController@edit');
//    Route::get('/estado/{id}/destroy',[
//	'uses'=>'EstadoController@destroy',
//	'as'=>'estado.destroy'
//	]);
    /******************************************************/
    

    Route::resource('estado', 'EstadoController');
    Route::resource('cliente', 'ClienteController');
    Route::resource('service', 'ServicioController');
    Route::resource('notas', 'NotaServicioController');
    
    
    //En pruebas
    Route::get('/service/{id}/destroy', [
        'uses' => 'ServicioController@destroy',
        'as' => 'service.destroy'
    ]);

    //Route::get('/notas/buscar/{ci}','NotaServicioController@buscar');

    Route::get('test', function() {
        return view('notas.create');
    });

    Route::post('buscli', 'NotaServicioController@buscarCliente');
    Route::post('itemservi', 'NotaServicioController@agregarServicio');
    Route::post('guardarnota', 'NotaServicioController@guardarNota');
    Route::post('quitarservi', 'NotaServicioController@quitarServicio');
});

resources/views/service/create.blade.php
@extends('layouts.admin');
	@section('content')
	<h3>Nuevo Servicio</h3>
	{!!Form::open(['route'=>'service.store', 'method'=>'POST'])!!}
	<div class="form-group">
		{!!Form::label('lbl_nombre','Nombre:')!!}
		{!!Form::text('nombre',null,['class'=>'form-control','placeholder'=>'Ingresa el Nombre.'])!!}
	</div>
	<div class="form-group">
		{!!Form::label('lbl_descripcion','Descripcion:')!!}
		{!!Form::textarea('descripcion',null,['class'=>'form-control','placeholder'=>'Ingresa su Descripcion.'])!!}
	</div>
	<div class="form-group">
		{!!Form::label('lbl_precio','Precio:')!!}
		{!!Form::text('precio',null,['class'=>'form-control','placeholder'=>'Ingresa el precio.'])!!}
	</div>
	{!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
	{!!Form::close()!!}
	@endsection

resources/views/service/edit.blade.php
@extends('layouts.admin');
@section('content')
<h3>Editar Servicio</h3>
{!!Form::model($service,['route'=>['service.update', $service->id],'method'=>'PUT'])!!}
	<div class="form-group">
		{!!Form::label('lbl_nombre','Nombre:')!!}
		{!!Form::text('nombre',null,['class'=>'form-control','placeholder'=>'Ingresa el Nombre.'])!!}
	</div>
	<div class="form-group">
		{!!Form::label('lbl_descripcion','Descripcion:')!!}
		{!!Form::textarea('descripcion',null,['class'=>'form-control','placeholder'=>'Ingresa su Descripcion.'])!!}
	</div>
	<div class="form-group">
		{!!Form::label('lbl_precio','Precio:')!!}
		{!!Form::text('precio',null,['class'=>'form-control','placeholder'=>'Ingresa el precio.'])!!}
	</div>
	{!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
	{!!Form::close()!!}
@endsection

resources/views/service/index.blade.php
@extends('layouts.admin')
@if(Session::has('message'))
<div class="alert alert-success alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  	{{Session::get('message')}}
</div>
@endif
@section('content')
<h3>Lista Servicios</h3>	
	<table class="table">
		<thead>
			<th>Nombre</th>
			<th>Descripcion</th>
			<th>Precio</th>
			<th>Accion</th>
		</thead>
		<tbody>
		@foreach($services as $service)
				<td>{{$service->nombre}}</td>
				<td>{{$service->descripcion}}</td>
				<td>{{$service->precio}}</td>
				<td>{!!link_to_route('service.edit', $title = 'Editar', $parameters = $service->id, $attributes = ['class'=>'btn btn-primary'])!!}
				{!!link_to_route('service.destroy', $title = 'Eliminar', $parameters = $service->id, $attributes = ['class'=>'btn btn-danger'])!!}
				</td>
		</tbody>
		@endforeach
	</table>
@endsection