app/Http/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | This route group applies the "web" middleware group to every route
  | it contains. The "web" middleware group is defined in your HTTP
  | kernel and includes session state, CSRF protection, and more.
  |
 */

Route::group(['middleware' => ['web']], function () {
    Route::auth();

    Route::get('/home', 'HomeController@index');

    Route::get('/', function () {
        return view('welcome');
    });
    
    
    /*Rutas Estado*****************************************/
//    Route::get('/estado','EstadoController@index');
//    Route::post('/estado/create','EstadoController@create');
    //Route::get('/estado','EstadoController@edit');
//    Route::get('/estado/{id}/destroy',[
//	'uses'=>'EstadoController@destroy',
//	'as'=>'estado.destroy'
//	]);
    /******************************************************/
    

    Route::resource('estado', 'EstadoController');
    Route::resource('cliente', 'ClienteController');
    Route::resource('service', 'ServicioController');
    Route::resource('notas', 'NotaServicioController');
    
    
    //En pruebas
    Route::get('/service/{id}/destroy', [
        'uses' => 'ServicioController@destroy',
        'as' => 'service.destroy'
    ]);

    //Route::get('/notas/buscar/{ci}','NotaServicioController@buscar');

    Route::get('test', function() {
        return view('notas.create');
    });

    Route::post('buscli', 'NotaServicioController@buscarCliente');
    Route::post('itemservi', 'NotaServicioController@agregarServicio');
    Route::post('guardarnota', 'NotaServicioController@guardarNota');
    Route::post('quitarservi', 'NotaServicioController@quitarServicio');
});

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $table = 'clientes';
    protected $fillable = ['id','empresa','nit','contacto','codigo','correo','direccion','celular','telefono','fecha_registro','latitud','longitud','id_estado'];
    
    public function Estados(){
    	return $this->hasMany('App\Estado');
    }

    public function getCliente($ci){
    	return Cliente::where('id',$id)->first();

    }
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Cliente;

class ClienteController extends Controller
{
    public function index(){
    	$clientes = Cliente::all();
    	return view('cliente.index')->with('clientes',$clientes);
    }

    public function create(){
    	return view('cliente.create'); 
    }

    public function store(Request $request){
    	Cliente::create([
    			'id'=>$request['id'],
    			'empresa'=>$request['empresa'],
    			'nit'=>$request['nit'],
                        'contacto'=>$request['contacto'],
                        'codigo'=>$request['codigo'],
                        'correo'=>$request['correo'],
                        'direccion'=>$request['direccion'],
                        'celular'=>$request['celular'],
                        'telefono'=>$request['telefono'],
                        'fecha_registro'=>$request['fecha_registro'],
                        'latitud'=>$request['latitud'],
                        'longitud'=>$request['longitud'],
                        'id_estado'=>$request['id_estado'],
    		]);
    	return redirect('/cliente')->with('message','ok');
    }
}

resources/views/cliente/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="row">
    <div class="col-md-11 col-md-offset-0">
        <div class="panel panel-default">
            <div class="panel-heading"><h3>Registrar cliente</h3></div>
            <div class="panel-body">
                {!!Form::open(['route'=>'cliente.store', 'method'=>'POST'])!!}
                <div class="form-group">
                    {!!Form::label('lbl_empresa','Empresa:')!!}
                    {!!Form::text('empresa',null,['class'=>'form-control','placeholder'=>'Ingresa nombre de la empresa'])!!}
                </div>
                <div class="form-group">
                    {!!Form::label('lbl_nit','NIT:')!!}
                    {!!Form::text('nit',null,['class'=>'form-control','placeholder'=>'Ingresa NIT de empresa'])!!}
                </div>
                <div class="form-group">
                    {!!Form::label('lbl_contacto','Contacto:')!!}
                    {!!Form::text('contacto',null,['class'=>'form-control','placeholder'=>'Ingrese nombre del contacto'])!!}
                </div>
                <div class="form-group">
                    {!!Form::label('lbl_codigo','Codigo:')!!}
                    {!!Form::text('codigo',null,['class'=>'form-control','placeholder'=>''])!!}
                </div>
                <div class="form-group">
                    {!!Form::label('lbl_correo','Correo:')!!}
                    {!!Form::text('correo',null,['class'=>'form-control','placeholder'=>'Ingrese gmail'])!!}
                </div>
                <div class="form-group">
                    {!!Form::label('lbl_direccion','Direccion:')!!}
                    {!!Form::text('direccion',null,['class'=>'form-control','placeholder'=>'Direccion de la empresa'])!!}
                </div>
                <div class="form-group">
                    {!!Form::label('lbl_celular','Cel:')!!}
                    {!!Form::text('celular',null,['class'=>'form-control','placeholder'=>'Numero de contacto'])!!}
                </div>
                <div class="form-group">
                    {!!Form::label('lbl_telefono','Telf:')!!}
                    {!!Form::text('telefono',null,['class'=>'form-control','placeholder'=>'Telefono de la empresa'])!!}
                </div>
                <div class="form-group">
                    {!!Form::label('lbl_fecha_registro','Fecha:')!!}
                    {!!Form::text('fecha_registro',null,['class'=>'form-control','placeholder'=>''])!!}
                </div>
                <div class="form-group">
                    {!!Form::label('lbl_latitud','Latitud:')!!}
                    {!!Form::text('latitud',null,['class'=>'form-control','placeholder'=>''])!!}
                </div>
                <div class="form-group">
                    {!!Form::label('lbl_longitud','Longitud:')!!}
                    {!!Form::text('longitud',null,['class'=>'form-control','placeholder'=>''])!!}
                </div>
                <div class="form-group">
                    {!!Form::label('lbl_id_estado','Estado:')!!}
                    {!!Form::text('id_estado',null,['class'=>'form-control','placeholder'=>''])!!}
                </div>
                {!!Form::submit('Registrar',['class'=>'btn btn-primary'])!!}
                {!!Form::close()!!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/cliente/index.blade.php
@extends('layouts.admin')
<?php $message = Session::get('message') ?>
@if($message == 'ok')
<div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    Cliente Registrado.
</div>
@endif
@section('content')
<div class="row">
    <div class="col-md-11 col-md-offset-0">
        <div class="panel panel-default">
            <div class="panel-heading"><h3>Lista de clientes</h3></div>
            <div class="panel-body">
                <table class="table">
                    <thead>
                    <th>ID</th>
                    <th>Empresa</th>
                    <th>NIT</th>
                    <th>Contacto</th>
                    <th>Estado</th>
                    <th>Accion</th>
                    </thead>
                    <tbody>
                        @foreach($clientes as $cliente)
                    <td>{{$cliente->id}}</td>
                    <td>{{$cliente->empresa}}</td>
                    <td>{{$cliente->nit}}</td>
                    <td>{{$cliente->contacto}}</td>
                    <td>{{$cliente->estado}}</td>
                    <td>
                        {!!link_to_route('cliente.edit', $title = 'Editar', $parameters = $cliente->id, $attributes = ['class'=>'btn btn-primary'])!!}
                        {!!link_to_route('cliente.destroy', $title = 'Eliminar', $parameters = $cliente->id, $attributes = ['class'=>'btn btn-danger'])!!}
                    </td>
                    </tbody>
                    @endforeach
                </table>
            </div>
        </div>
    </div>
</div>
@endsection